import * as Constants from '../../constants';
import Config from '../../config';

const {
    env: { IS_DE_LANG_ENV },
} = Config;

const deReferences = [
    {
        title: `case.weshare.hero.project`,
        description: `case.weshare.hero.title`,
        category: Constants.categories.TRAVEL,
        image: 'references/items/weshare.jpg',
        link: Config.routes.references.weshare,
    },
    {
        title: `references.wwf.title`,
        description: `references.wwf.description`,
        category: Constants.categories.DIGITALIZATION,
        image: 'references/items/wwf.jpg',
        link: Config.routes.references.wwf,
    },
    {
        title: `references.bundestag.title`,
        description: `references.bundestag.description`,
        category: Constants.categories.DIGITALIZATION,
        image: 'references/items/bundestag.jpg',
        link: Config.routes.references.bundestag,
    },
    {
        title: `references.tmobile.title`,
        description: `references.tmobile.description`,
        category: Constants.categories.E_COMMERCE,
        image: 'references/items/tmobile-en.jpg',
        link: Config.routes.references.tmobile,
    },
    {
        title: `references.samsung.title`,
        description: `references.samsung.description`,
        category: Constants.categories.DIGITALIZATION,
        image: 'references/items/samsung-en.jpg',
        link: Config.routes.references.samsung,
    },
    {
        title: `references.cosmo.title`,
        description: `references.cosmo.description`,
        category: Constants.categories.TRAVEL,
        image: 'references/items/cosmo.jpg',
        link: Config.routes.references.cosmo,
    },
    {
        title: `references.deliveryhero.title`,
        description: `references.deliveryhero.description`,
        category: Constants.categories.DELIVERY,
        image: 'references/items/deliveryhero.jpg',
        link: Config.routes.references.deliveryhero,
    },
    {
        title: `references.simplifa.title`,
        description: `references.simplifa.description`,
        category: Constants.categories.DIGITALIZATION,
        image: 'references/items/simplifa.jpg',
        link: Config.routes.references.simplifa,
    },
    {
        title: `references.tapito.title`,
        description: `references.tapito.description`,
        category: Constants.categories.DIGITALIZATION,
        image: 'references/items/tapito-en.jpg',
        link: Config.routes.references.tapito,
    },
    {
        title: `references.ventusky.title`,
        description: `references.ventusky.description`,
        category: Constants.categories.DIGITALIZATION,
        image: 'references/items/ventusky-en.jpg',
        link: Config.routes.references.ventusky,
    },
    {
        title: `references.grenke.title`,
        description: `references.grenke.description`,
        category: Constants.categories.FINANCE,
        image: 'references/items/grenke.jpg',
        link: Config.routes.references.grenke,
    },
    {
        title: `references.equa.title`,
        description: `references.equa.description`,
        category: Constants.categories.FINANCE,
        image: 'references/items/equa.jpg',
        link: Config.routes.references.equa,
    },
    {
        title: `references.zonky.title`,
        description: `references.zonky.description`,
        category: Constants.categories.FINANCE,
        image: 'references/items/zonky-en.jpg',
        link: Config.routes.references.zonky,
    },
    {
        title: `references.hi5.title`,
        description: `references.hi5.description`,
        category: Constants.categories.E_COMMERCE,
        image: 'references/items/hi5.jpg',
        link: Config.routes.references.hi5,
    },
    {
        title: `references.ethereum.title`,
        description: `references.ethereum.description`,
        category: Constants.categories.FINANCE,
        image: 'references/items/ethereum.jpg',
        link: Config.routes.references.ethereum,
    },
];
const csReferences = [
    {
        title: `references.flashsport.title`,
        description: `references.flashsport.description`,
        category: Constants.categories.NEWS,
        image: 'references/items/flashsport.jpg',
        link: Config.routes.references.flashsport,
    },
    {
        title: `case.weshare.hero.project`,
        description: `case.weshare.hero.title`,
        category: Constants.categories.TRAVEL,
        image: 'references/items/weshare.jpg',
        link: Config.routes.references.weshare,
    },
    {
        title: `references.wwf.title`,
        description: `references.wwf.description`,
        category: Constants.categories.DIGITALIZATION,
        image: 'references/items/wwf.jpg',
        link: Config.routes.references.wwf,
    },
    {
        title: `references.citymove.title`,
        description: `references.citymove.description`,
        category: Constants.categories.TRAVEL,
        image: 'references/items/citymove.jpg',
        link: Config.routes.references.citymove,
    },
    {
        title: `references.cme.title`,
        description: `references.cme.description`,
        category: Constants.categories.DIGITALIZATION,
        image: 'references/items/cme.jpg',
        link: Config.routes.references.cme,
    },
    {
        title: `case.hopi.hero.project`,
        description: `case.hopi.hero.title`,
        category: Constants.categories.DIGITALIZATION,
        image: 'references/items/hopi.jpg',
        link: Config.routes.references.hopi,
    },
    {
        title: `references.cosmo.title`,
        description: `references.cosmo.description`,
        category: Constants.categories.DELIVERY,
        image: 'references/items/cosmo.jpg',
        link: Config.routes.references.cosmo,
    },
    {
        title: `references.bundestag.title`,
        description: `references.bundestag.description`,
        category: Constants.categories.DIGITALIZATION,
        image: 'references/items/bundestag.jpg',
        link: Config.routes.references.bundestag,
    },
    {
        title: `references.moneystep.title`,
        description: `references.moneystep.description`,
        category: Constants.categories.FINANCE,
        image: 'references/items/moneystep.jpg',
        link: Config.routes.references.moneyStep,
    },
    {
        title: `references.kosik.title`,
        description: `references.kosik.description`,
        category: Constants.categories.E_COMMERCE,
        image: 'references/items/kosik.jpg',
        link: Config.routes.references.kosik,
    },
    {
        title: `references.dpnk.title`,
        description: `references.dpnk.description`,
        category: Constants.categories.TRAVEL,
        image: 'references/items/dpnk.jpg',
        link: Config.routes.references.dpnk,
    },
    {
        title: `references.zonky.title`,
        description: `references.zonky.description`,
        category: Constants.categories.FINANCE,
        image: 'references/items/zonky.jpg',
        link: Config.routes.references.zonky,
    },
    {
        title: `references.criticalStates.title`,
        description: `references.criticalStates.description`,
        category: Constants.categories.DIGITALIZATION,
        image: 'references/items/critical-states.png',
        link: Config.routes.references.criticalStates,
    },
    {
        title: `references.kolofix.title`,
        description: `references.kolofix.description`,
        category: Constants.categories.TRAVEL,
        image: 'references/items/kolofix.jpg',
        link: Config.routes.references.kolofix,
    },
    {
        title: `references.equa.title`,
        description: `references.equa.description`,
        category: Constants.categories.FINANCE,
        image: 'references/items/equa.jpg',
        link: Config.routes.references.equa,
    },
    {
        title: `references.tmobile.title`,
        description: `references.tmobile.description`,
        category: Constants.categories.E_COMMERCE,
        image: 'references/items/tmobile.jpg',
        link: Config.routes.references.tmobile,
    },
    {
        title: `references.bazos.title`,
        description: `references.bazos.description`,
        category: Constants.categories.E_COMMERCE,
        image: 'references/items/bazos.jpg',
        link: Config.routes.references.bazos,
    },
    {
        title: `references.deliveryhero.title`,
        description: `references.deliveryhero.description`,
        category: Constants.categories.DELIVERY,
        image: 'references/items/deliveryhero.jpg',
        link: Config.routes.references.deliveryhero,
    },
    {
        title: `references.hi5.title`,
        description: `references.hi5.description`,
        category: Constants.categories.E_COMMERCE,
        image: 'references/items/hi5.jpg',
        link: Config.routes.references.hi5,
    },
    {
        title: `references.skodamoped.title`,
        description: `references.skodamoped.description`,
        category: Constants.categories.DIGITALIZATION,
        image: 'references/items/skodamoped.jpg',
        link: Config.routes.references.skodamoped,
    },
    {
        title: `references.samsung.title`,
        description: `references.samsung.description`,
        category: Constants.categories.DIGITALIZATION,
        image: 'references/items/samsung.jpg',
        link: Config.routes.references.samsung,
    },
    {
        title: `references.ventusky.title`,
        description: `references.ventusky.description`,
        category: Constants.categories.NEWS,
        image: 'references/items/ventusky.jpg',
        link: Config.routes.references.ventusky,
    },
    {
        title: `references.simplifa.title`,
        description: `references.simplifa.description`,
        category: Constants.categories.DIGITALIZATION,
        image: 'references/items/simplifa.jpg',
        link: Config.routes.references.simplifa,
    },
];
const enReferences = [
    {
        title: `references.flashsport.title`,
        description: `references.flashsport.description`,
        category: Constants.categories.NEWS,
        image: 'references/items/flashsport-en.jpg',
        link: Config.routes.references.flashsport,
    },
    {
        title: `case.weshare.hero.project`,
        description: `case.weshare.hero.title`,
        category: Constants.categories.TRAVEL,
        image: 'references/items/weshare.jpg',
        link: Config.routes.references.weshare,
    },
    {
        title: `references.wwf.title`,
        description: `references.wwf.description`,
        category: Constants.categories.DIGITALIZATION,
        image: 'references/items/wwf.jpg',
        link: Config.routes.references.wwf,
    },
    {
        title: `references.citymove.title`,
        description: `references.citymove.description`,
        category: Constants.categories.TRAVEL,
        image: 'references/items/citymove.jpg',
        link: Config.routes.references.citymove,
    },
    {
        title: `references.cme.title`,
        description: `references.cme.description`,
        category: Constants.categories.DIGITALIZATION,
        image: 'references/items/cme.jpg',
        link: Config.routes.references.cme,
    },
    {
        title: `case.hopi.hero.project`,
        description: `case.hopi.hero.title`,
        category: Constants.categories.DIGITALIZATION,
        image: 'references/items/hopi.jpg',
        link: Config.routes.references.hopi,
    },
    {
        title: `references.cosmo.title`,
        description: `references.cosmo.description`,
        category: Constants.categories.DELIVERY,
        image: 'references/items/cosmo.jpg',
        link: Config.routes.references.cosmo,
    },
    {
        title: `references.bundestag.title`,
        description: `references.bundestag.description`,
        category: Constants.categories.DIGITALIZATION,
        image: 'references/items/bundestag.jpg',
        link: Config.routes.references.bundestag,
    },
    {
        title: `references.moneystep.title`,
        description: `references.moneystep.description`,
        category: Constants.categories.FINANCE,
        image: 'references/items/moneystep.jpg',
        link: Config.routes.references.moneyStep,
    },
    {
        title: `references.kosik.title`,
        description: `references.kosik.description`,
        category: Constants.categories.E_COMMERCE,
        image: 'references/items/kosik.jpg',
        link: Config.routes.references.kosik,
    },
    {
        title: `references.zonky.title`,
        description: `references.zonky.description`,
        category: Constants.categories.FINANCE,
        image: 'references/items/zonky-en.jpg',
        link: Config.routes.references.zonky,
    },
    {
        title: `references.criticalStates.title`,
        description: `references.criticalStates.description`,
        category: Constants.categories.DIGITALIZATION,
        image: 'references/items/critical-states.png',
        link: Config.routes.references.criticalStates,
    },
    {
        title: `references.kolofix.title`,
        description: `references.kolofix.description`,
        category: Constants.categories.TRAVEL,
        image: 'references/items/kolofix.jpg',
        link: Config.routes.references.kolofix,
    },
    {
        title: `references.equa.title`,
        description: `references.equa.description`,
        category: Constants.categories.FINANCE,
        image: 'references/items/equa.jpg',
        link: Config.routes.references.equa,
    },
    {
        title: `references.tmobile.title`,
        description: `references.tmobile.description`,
        category: Constants.categories.E_COMMERCE,
        image: 'references/items/tmobile-en.jpg',
        link: Config.routes.references.tmobile,
    },
    {
        title: `references.bazos.title`,
        description: `references.bazos.description`,
        category: Constants.categories.E_COMMERCE,
        image: 'references/items/bazos.jpg',
        link: Config.routes.references.bazos,
    },
    {
        title: `references.deliveryhero.title`,
        description: `references.deliveryhero.description`,
        category: Constants.categories.DELIVERY,
        image: 'references/items/deliveryhero.jpg',
        link: Config.routes.references.deliveryhero,
    },
    {
        title: `references.hi5.title`,
        description: `references.hi5.description`,
        category: Constants.categories.E_COMMERCE,
        image: 'references/items/hi5.jpg',
        link: Config.routes.references.hi5,
    },
    {
        title: `references.skodamoped.title`,
        description: `references.skodamoped.description`,
        category: Constants.categories.DIGITALIZATION,
        image: 'references/items/skodamoped.jpg',
        link: Config.routes.references.skodamoped,
    },
    {
        title: `references.samsung.title`,
        description: `references.samsung.description`,
        category: Constants.categories.DIGITALIZATION,
        image: 'references/items/samsung-en.jpg',
        link: Config.routes.references.samsung,
    },
    {
        title: `references.ventusky.title`,
        description: `references.ventusky.description`,
        category: Constants.categories.NEWS,
        image: 'references/items/ventusky-en.jpg',
        link: Config.routes.references.ventusky,
    },
    {
        title: `references.simplifa.title`,
        description: `references.simplifa.description`,
        category: Constants.categories.DIGITALIZATION,
        image: 'references/items/simplifa.jpg',
        link: Config.routes.references.simplifa,
    },
];

const referencesList = IS_DE_LANG_ENV
    ? {
          de: deReferences,
      }
    : {
          en: enReferences,
          cs: csReferences,
      };

export const references = Object.assign(
    ...Object.keys(referencesList).map(key => ({
        [key]: referencesList[key].map((reference, index) => {
            reference.id = index;
            return reference;
        }),
    })),
);
